### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [Abigailpormes/Secret_html#1]
Oke dari struktur ada oke tetapi ada kekurang seperti ga adanya form dan penyambungan JavaScript. Submission Approved dan goodluck belajar CSS

**Comment by Abigailpormes** [comment]
Baik kak, akan saya lengkapi dan sambungkan ke JS.
Terimakasih kak.

Pada tanggal Kam, 25 Mei 2023 21:56, Dhaffa Agus ***@***.***>
menulis:
